name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Versión de Java deseada
          distribution: 'adopt'  # Distribución de Java (adoptopenjdk)
          architecture: 'x64'

      - name: Build with Maven
        run: |
          mvn clean install --batch-mode --errors

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ururacergestion'  # Nombre de tu Azure Web App
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_406529b6be6f4991a1033c04a74c410c }}
          package: '*.jar'
